export { default as Update } from './Update'
export { default as All } from './All'
export { default as Search } from './Search'
export { default as NotFound } from './NotFound'
export { default as Login } from './Login'
export { default as Person} from './Person'
